packages:
  - packages/*
  - playgrounds/*

catalog:
  '@antfu/eslint-config': 6.6.1
  '@nuxt/kit': ^4.2.2
  '@nuxt/module-builder': 1.0.1
  '@nuxt/schema': 4.2.2
  '@vitejs/plugin-vue': 5.2.4
  '@vitest/coverage-v8': 3.1.4
  '@vue/test-utils': 2.4.6
  bumpp: 10.1.1
  defu: ^6.1.4
  eslint: 9.27.0
  happy-dom: 17.4.7
  installed-check: 9.3.0
  lint-staged: 16.0.0
  nuxt: 4.2.2
  rou3: ^0.6.1
  simple-git-hooks: 2.13.0
  tsx: 4.19.4
  typescript: 5.8.3
  ufo: ^1.6.1
  unbuild: 3.5.0
  vitest: 3.1.4
  vue-tsc: 3.1.8
