packages:
  - packages/*
  - playgrounds/*

catalog:
  '@antfu/eslint-config': 6.6.1
  '@nuxt/kit': ^4.2.2
  '@nuxt/module-builder': 1.0.2
  '@nuxt/schema': 4.2.2
  '@vitejs/plugin-vue': 6.0.2
  '@vitest/coverage-v8': 4.0.15
  '@vue/test-utils': 2.4.6
  bumpp: 10.3.2
  defu: ^6.1.4
  eslint: 9.39.1
  happy-dom: 20.0.11
  installed-check: 9.3.0
  lint-staged: 16.2.7
  nuxt: 4.2.2
  rou3: ^0.7.11
  simple-git-hooks: 2.13.1
  tsx: 4.21.0
  typescript: 5.9.3
  ufo: ^1.6.1
  unbuild: 3.6.1
  vitest: 4.0.15
  vue-tsc: 3.1.8
